# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: geofence/geofence.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17geofence/geofence.proto\x12\x13mavsdk.rpc.geofence\"4\n\x05Point\x12\x14\n\x0clatitude_deg\x18\x01 \x01(\x01\x12\x15\n\rlongitude_deg\x18\x02 \x01(\x01\"\xb2\x01\n\x07Polygon\x12*\n\x06points\x18\x01 \x03(\x0b\x32\x1a.mavsdk.rpc.geofence.Point\x12:\n\nfence_type\x18\x02 \x01(\x0e\x32&.mavsdk.rpc.geofence.Polygon.FenceType\"?\n\tFenceType\x12\x18\n\x14\x46\x45NCE_TYPE_INCLUSION\x10\x00\x12\x18\n\x14\x46\x45NCE_TYPE_EXCLUSION\x10\x01\"Y\n\x15UploadGeofenceRequest\x12\x10\n\x08\x64rone_id\x18\x01 \x01(\x05\x12.\n\x08polygons\x18\x02 \x03(\x0b\x32\x1c.mavsdk.rpc.geofence.Polygon\"V\n\x16UploadGeofenceResponse\x12<\n\x0fgeofence_result\x18\x01 \x01(\x0b\x32#.mavsdk.rpc.geofence.GeofenceResult\"(\n\x14\x43learGeofenceRequest\x12\x10\n\x08\x64rone_id\x18\x02 \x01(\x05\"U\n\x15\x43learGeofenceResponse\x12<\n\x0fgeofence_result\x18\x01 \x01(\x0b\x32#.mavsdk.rpc.geofence.GeofenceResult\"\xa1\x02\n\x0eGeofenceResult\x12:\n\x06result\x18\x01 \x01(\x0e\x32*.mavsdk.rpc.geofence.GeofenceResult.Result\x12\x12\n\nresult_str\x18\x02 \x01(\t\"\xbe\x01\n\x06Result\x12\x12\n\x0eRESULT_UNKNOWN\x10\x00\x12\x12\n\x0eRESULT_SUCCESS\x10\x01\x12\x10\n\x0cRESULT_ERROR\x10\x02\x12\"\n\x1eRESULT_TOO_MANY_GEOFENCE_ITEMS\x10\x03\x12\x0f\n\x0bRESULT_BUSY\x10\x04\x12\x12\n\x0eRESULT_TIMEOUT\x10\x05\x12\x1b\n\x17RESULT_INVALID_ARGUMENT\x10\x06\x12\x14\n\x10RESULT_NO_SYSTEM\x10\x07\x32\xe8\x01\n\x0fGeofenceService\x12k\n\x0eUploadGeofence\x12*.mavsdk.rpc.geofence.UploadGeofenceRequest\x1a+.mavsdk.rpc.geofence.UploadGeofenceResponse\"\x00\x12h\n\rClearGeofence\x12).mavsdk.rpc.geofence.ClearGeofenceRequest\x1a*.mavsdk.rpc.geofence.ClearGeofenceResponse\"\x00\x42#\n\x12io.mavsdk.geofenceB\rGeofenceProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'geofence.geofence_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\022io.mavsdk.geofenceB\rGeofenceProto'
  _globals['_POINT']._serialized_start=48
  _globals['_POINT']._serialized_end=100
  _globals['_POLYGON']._serialized_start=103
  _globals['_POLYGON']._serialized_end=281
  _globals['_POLYGON_FENCETYPE']._serialized_start=218
  _globals['_POLYGON_FENCETYPE']._serialized_end=281
  _globals['_UPLOADGEOFENCEREQUEST']._serialized_start=283
  _globals['_UPLOADGEOFENCEREQUEST']._serialized_end=372
  _globals['_UPLOADGEOFENCERESPONSE']._serialized_start=374
  _globals['_UPLOADGEOFENCERESPONSE']._serialized_end=460
  _globals['_CLEARGEOFENCEREQUEST']._serialized_start=462
  _globals['_CLEARGEOFENCEREQUEST']._serialized_end=502
  _globals['_CLEARGEOFENCERESPONSE']._serialized_start=504
  _globals['_CLEARGEOFENCERESPONSE']._serialized_end=589
  _globals['_GEOFENCERESULT']._serialized_start=592
  _globals['_GEOFENCERESULT']._serialized_end=881
  _globals['_GEOFENCERESULT_RESULT']._serialized_start=691
  _globals['_GEOFENCERESULT_RESULT']._serialized_end=881
  _globals['_GEOFENCESERVICE']._serialized_start=884
  _globals['_GEOFENCESERVICE']._serialized_end=1116
# @@protoc_insertion_point(module_scope)
